### ISSUE TITLE
Paging has strange behavior in some cases

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/Coalesce#380]
It seems weird that if I backspace the page number, it will show me on page -9 - 0 which is non-existent. I would expect that it would bring me to page 1.

Also, if I am on page (lets say 80/100), and I apply filters so there are only 10 pages of results, it keeps me on page "80", and also lets me still type in a seemingly invalid number (ex: 30). I would expect it would correct the number I entered in to the closest valid number (if I type in 30 when there are only 10 pages, it would bring me to page 10).

https://github.com/IntelliTect/Coalesce/assets/22186029/a523b574-8649-4fb8-8ca8-7ce1b8045bf7

**Comment by ascott18** [comment]
Issue 1 is a clear bug - will fix.

Issue 2 gets tricky because if we start modifying the parameters when we get a result back, any list that is using auto load will get loaded twice when its $page gets capped out. I may just implement this visually in c-list-page without actually modifying the parameters on the list.
